ALTER TABLE documents ADD COLUMN IF NOT EXISTS owner_user_id BIGINT REFERENCES users(id);

ALTER TABLE documents DROP COLUMN IF EXISTS company_id;
ALTER TABLE documents DROP COLUMN IF EXISTS content;
ALTER TABLE documents DROP COLUMN IF EXISTS embedding;

ALTER TABLE documents ADD COLUMN IF NOT EXISTS tag VARCHAR(20) DEFAULT '일반';
ALTER TABLE documents ADD COLUMN IF NOT EXISTS s3_key VARCHAR(500);
ALTER TABLE documents ADD COLUMN IF NOT EXISTS file_type VARCHAR(20);
